In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('per.csv', encoding='utf8')
data.head()

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

In [4]:
with open('stopwords.txt', encoding='utf8') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '...',
 '....',
 '/',
 ':',
 '<',
 '=',
 '>',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'ء',
 'آاو و و و',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسانی',
 'آسيب پذيرند',
 'آسیب',
 'آسیب پذیرند',
 'آشكارا',
 'آشنايند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن ها',
 'آن گاه',
 'آنان',
 'آناني',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنكه',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان كه',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهاي',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آيا',
 'آيد',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'ابدا',
 'ابلهانه',
 'ات',
 'اتفاقا',
 'اثر',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احياناً',
 'احیانا',
 'احیاناً',
 'اخ',
 'اختصارا',

In [ ]:
!pip install nltk hazm

In [9]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kavia\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

2976

In [11]:
import hazm
stemmer = hazm.Stemmer()

In [12]:
stemmer.stem('کتاب‌ها')

'کتاب'

In [13]:
from hazm import word_tokenize

In [14]:
dataset = pd.DataFrame(columns=('title_body', 'category'))
for index, row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    dataset.loc[index] = {
        'title_body': ' '.join(title_body_tokenized_filtered_stemmed),
        'category': row['Category2'].replace('\n', '')
    }

In [15]:
dataset.head()

title_body category
0  وزير علو درجمع استاد نمونه سن بازنشستگي استاد ...   آموزشي
1  گردهمايي دانش‌آموختگ موسسه آموز عالي سوره برگز...   آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...   آموزشي
3  هماي يكروزه آسيب مفهو روابط عمومي بابلسر برگزا...  اجتماعي
4  وضعي اقتصادي تحصيل والدين مهمترين عوامل موفقي ...   آموزشي

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
vectorizer = TfidfVectorizer()
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [ ]:
import pickle
with open('lion_v.jsdh', 'wb') as f:
    pickle.dump(vectorizer, f)

In [18]:
X = vectorizer.transform(dataset['title_body'])

In [19]:
X

<10999x60631 sparse matrix of type '<class 'numpy.float64'>'
	with 1556652 stored elements in Compressed Sparse Row format>

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [22]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [23]:
len(y)

10999

In [25]:
np.shape(X)

(10999, 60631)

In [26]:
np.shape(y)

(10999,)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [29]:
from sklearn import svm

In [30]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC()

In [31]:
svmc.score(X_test, y_test)

0.8352727272727273

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88       274
           1       0.58      0.65      0.61       247
           2       0.82      0.77      0.79       264
           3       0.81      0.94      0.87       231
           4       0.93      0.91      0.92       245
           5       0.84      0.68      0.75       254
           6       0.77      0.71      0.74       230
           7       0.83      0.86      0.85       232
           8       0.86      0.85      0.85       252
           9       0.95      0.93      0.94       265
          10       0.96      0.97      0.97       256

    accuracy                           0.84      2750
   macro avg       0.84      0.83      0.83      2750
weighted avg       0.84      0.84      0.84      2750



In [34]:
print(confusion_matrix(y_test, y_pred))

[[249   8   0   7   0   1   9   0   0   0   0]
 [ 14 161  10  12   2   5  14  11   9   5   4]
 [  1  36 203   0   0   4   8   7   2   3   0]
 [  1   8   1 216   0   0   5   0   0   0   0]
 [  3   4   1   0 223   6   2   3   3   0   0]
 [  5  12  20   5   8 173   5   3  20   2   1]
 [ 15  10   7  24   0   5 163   5   0   0   1]
 [  2  12   2   1   2   3   5 200   2   1   2]
 [  2  12   1   1   5   7   2   6 214   1   1]
 [  0  11   1   1   0   2   0   3   0 247   0]
 [  0   3   1   1   0   1   0   2   0   0 248]]


In [24]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']


In [ ]:
# MasoudKaviani.ir